### ISSUE TITLE
Start Testnet section

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#11]
Add a new testnets section to the docs.

Add two pages there:
* Demo Net
* Build Requirements

## Demo Net page

Demo Net should contain info to point to how to deploy to the current demo net, as well as the binaries / client libs involved:

* `wasmd v0.9.1`
* `cosmjs v0.21.1`

Client endpoints (from [@cosmjs/cli](https://github.com/CosmWasm/cosmjs/blob/master/packages/cli/examples/helpers.ts)):

* https://lcd.demo-09.cosmwasm.com
* https://rpc.demo-09.cosmwasm.com
* https://faucet.demo-09.cosmwasm.com/credit (point to [faucet usage docs](https://github.com/CosmWasm/cosmjs/tree/master/packages/faucet#using-the-faucet)

Show how to connect from local node:

* P2P endpoint: p2p.demo-09.cosmwasm.com:26656 
* Node ID: (from `wasmd tendermint show-node-id`): `26c9c79dc62b5ddc753bb9fcce022fcc98b5a8cf`
* Genesis: `curl https://rpc.demo-09.cosmwasm.com/genesis | jq .result.genesis`

Explain how to run with the official docker file (also use this locally and connect to the p2p node to show we can connect and sync)

## Build Requirements

System requirements: We use a Digital Ocean 2CPU,4GB instance - consider that as good basis (see [demo-net setup](https://github.com/ethanfrey/demo-net/blob/master/terraform/variables.tf))

Building code may require larger instances, especially if you want to build a static instance (recompile rust code).

Simplest: 

Use docker image, or build locally: https://github.com/CosmWasm/wasmd/#dockerized

Bare Metal:

Option 1 (prefered - static binary - Linux only): 

* Download Dockerfile / build locally
* Copy the static binary out of it. (Try a command to do so)
* Use that static binary on any bare metal linux box

Constructing this is a tricky process and involves using alpine linux and recompiling the rust dependencies as static libs. I suggest you use the Dockerfile for that

Option 2: (dev-style: dynamic binary - works on Linux and OSX)

* Compile dev build (`make build`). 
* `ldd build/wasmd`
  * notice the line like: `libgo_cosmwasm.so => /home/USERNAME/go/pkg/mod/github.com/!cosm!wasm/go-cosmwasm@v0.9.1/api/libgo_cosmwasm.so`
  * that file must be in the library path along with wasmd
* copy `wasmd` to any location on the target system (that will run the node)
* copy `libgo_cosmwasm.so` (path above) to the target system under  `/usr/lib/libgo_cosmwasm.so

**Comment by webmaster128** [comment]
Since this lives under the cosmwasm.com domain/documentation, I assume this is not for the gaia testnet, right?

**Comment by ethanfrey** [comment]
This is general documentation for our networks right now (how to connect, how to use), as well as a list of endpoints for the testnets we run.

I would focus on our public testnet (demo net now, later the Aug 11th one) for devs, but I would just make a page here for the gaia testnet to keep it simple. They can all use the same references on how to build validators and connect
