### ISSUE TITLE
Coral -> Corald problem

### ISSUE THREAD

**Issue by gelinger777** [CosmWasm/docs-deprecated-2023#123]
In docs you have commands which do not work anymore 

https://docs.cosmwasm.com/getting-started/setting-env.html   

For example coral command which is now corald and also as I was told config command does not work anymore. 
Could you fix that?

**Comment by alpe** [comment]
This is correct. All examples should use the `wasmd` command now.

**Comment by gelinger777** [comment]
ok thanks
