### ISSUE TITLE
Add Dev Docs for Testnets

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#13]
Builds on #11 

Add another section focused on devs:

* Describe to how to deploy contracts with cli and cosmjs (info for example contract is [here](https://docs.cosmwasm.com/getting-started/using-the-sdk.html) and [here](https://docs.cosmwasm.com/getting-started/first-demo.html) - let's pull out some general helpers from that)
* Show how to use the faucet (both with [curl](https://github.com/CosmWasm/cosmjs/tree/master/packages/faucet#using-the-faucet) and with [cosmjs](https://github.com/CosmWasm/cosmjs/blob/master/packages/cli/examples/helpers.ts#L83-L87))
* Link to code explorer (eg. https://demonet.wasm.glass)

Later, extend this:

* Link to block explorer (to be connected - leave placeholder)
* Link to wallet (to be connected - leave placeholder)
* Link to instructions how to write dApp (to be done #14 )

**Comment by orkunkl** [comment]
I think this issue will cause documentation duplication. There are two options I see:
1. Extend [cosmos sdk page](https://docs.cosmwasm.com/getting-started/using-the-sdk.html)(maybe rename it as well) and point devs from testnet documentation to there
2. Simply demonstrate uploading a single contract. But this will cause duplication again.

I suggest we keep the `Testnet` section for explaining how to join the testnets and the list of active testnets alongside the RPC, SEED apis. And organize/rewrite  `Getting Started` part and direct devs from join the testnet to the section. @ethanfrey

**Comment by ethanfrey** [comment]
Fair enough. Let's hold off for now. And think about how to avoid dups

**Comment by orkunkl** [comment]
Related to https://github.com/CosmWasm/docs2/issues/5. 
We need this documentation ASAP. The best approach would be not waiting for finishing `CosmWasm for dummies`.
I will reorganize the current documentation as @willclarktech mentioned. Then I will direct users to smart contract documentation from the end of testnet docs.

**Comment by ethanfrey** [comment]
That sounds good. Once everything is reorganized and in a smoother onboarding process, it will probably be more obvious exactly what docs are missing

**Comment by orkunkl** [comment]
This task has been dangling for some time. Let's close it.
