### ISSUE TITLE
Add docs on how to write a dApp

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#14]
* Point to [name-app code](https://gtithub.com/CosmWasm/name-app) and [deployment](https://cosmwasm.github.io/name-app) for first example (once updated to CosmWasm v0.10.0 and CosmJS 0.22).
* Explain a bit of the code (and clean it up?)
* Maybe point to [starport](https://github.com/tendermint/starport) if they add CosmWasm support.

**Comment by orkunkl** [comment]
Related to https://github.com/CosmWasm/docs2/issues/8

**Comment by fadeev** [comment]
@ethanfrey we've actually added a basic CosmWasm suport to Starport. Running `starport add wasm` will modify `app/app.go` and `cmd/appcli/main.go` files.

Some notes on this:

https://www.notion.so/fadeev/Smart-contracts-with-CosmWasm-c6fbcd584b78437a843e738b922dc108

**Comment by ethanfrey** [comment]
Wow, awesome work @fadeev you are flying :rocket: 

We should have `wasmd` `v0.10.0` (based on launchpad) and CosmJS `v0.22.0` out later this week, and I would love to discuss how to auto-build scaffolfing UI for contracts. (We have JSON schemas from them and @webmaster128 has done work before to generate type-script schemas and a query form programmatically). I'm sure you are super busy, but when you have time for a chat on this, I'd be happy

**Comment by fadeev** [comment]
@ethanfrey Thank you, CosmWasm looks amazing! 🙂 I've replied in Slack.
