### ISSUE TITLE
Adapt getting started section to 0.13

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#148]
I will adapt `getting started` but first 
- [x] https://github.com/CosmWasm/cosmwasm-examples/pull/116 needs to be merged @ethanfrey 
- [x] A cosmwasm-examples new release cut
- [x] For making changes here https://docs.cosmwasm.com/0.13/getting-started/interact-with-contract.html cosmjs v0.24 should be released. We cannot push js team to release just for this. I can put a note there this part does not work until v0.24 is released then take care of it later

**Comment by ethanfrey** [comment]
The examples are ready.
Let's get the code and wasmd commands updated and merged.

cosmjs may have larger changes (overhaul of scope of @cosmjs/cli): https://github.com/cosmos/cosmjs/issues/621

**Comment by orkunkl** [comment]
This has been stale. Need to fix helpers.ts
