### ISSUE TITLE
missing contract.wasm file

### ISSUE THREAD

**Issue by hxrts** [CosmWasm/docs-deprecated-2023#164]
`RES=$(wasmd tx wasm store contract.wasm --from fred $TXFLAG -y)`

there is no "contract.wasm" file in the escrow directory or any subfolders.

`> find . | grep "\.wasm$"`

gives me the following:

```
./artifacts/cw_escrow.wasm
./target/wasm32-unknown-unknown/release/cw_escrow.wasm
./target/wasm32-unknown-unknown/release/deps/cw_escrow.wasm
```

**Comment by diyahir** [comment]
I am also having the same issue, were you able to resolve this?

**Comment by harryscholes** [comment]
```
cp target/wasm32-unknown-unknown/release/cw_escrow.wasm contract.wasm
wasmd tx wasm store contract.wasm ...
```

or

```
cd target/wasm32-unknown-unknown/release
wasmd tx wasm store cw_escrow.wasm
```

worked for me

**Comment by orkunkl** [comment]
Thanks for pointing out. fixing this
