### ISSUE TITLE
Inconsistency between documentation and repository directory structure

### ISSUE THREAD

**Issue by matthiasgeihs** [CosmWasm/docs-deprecated-2023#176]
At https://docs.cosmwasm.com/0.13/getting-started/compile-contract.html:
```
git clone https://github.com/CosmWasm/cosmwasm-examples
cd cosmwasm-examples/escrow
```

At https://github.com/CosmWasm/cosmwasm-examples @16eaa84 the directory `cosmwasm-examples/escrow` does not exist.

**Comment by orkunkl** [comment]
Thanks for pointing out, solved this one
