### ISSUE TITLE
Investigate keplr wallet

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#19]

**Comment by ethanfrey** [comment]
@willclarktech did some work on integrating this and had a nice video.

If you have any questions you can ask him. But yeah, just running and installing from google chrome store should be good to get an idea of how it works. And is good enough for now

**Comment by ethanfrey** [comment]
We now have full integration in cosmjs and this is being documented here: https://github.com/CosmWasm/dApps/pull/59
