### ISSUE TITLE
Add new CosmWasm logo

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#2]
Please update the logo in the docs and deploy it with `./deploy.sh`

![photo_2020-07-20_11-47-57](https://user-images.githubusercontent.com/5689864/87924261-ebdc6100-ca7e-11ea-8978-c9c65c2bd130.jpg)

**Comment by webmaster128** [comment]
The quality of this image is not great. Can we get a PNG?

**Comment by ethanfrey** [comment]
Yeah, I will try to find the original

**Comment by orkunkl** [comment]
Let's keep several versions with different resolutions of the logo somewhere accessible to public. It will be requested many times.

**Comment by ethanfrey** [comment]
@orkunkl I pushed all versions of the original logos here: https://github.com/CosmWasm/docs2/tree/add_logos/.vuepress/public/logo

You can continue on that branch and make a PR with them integrated.
