### ISSUE TITLE
CosmJS v0.21.2 not fount

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#21]
In [using the sdk](https://github.com/CosmWasm/docs2/blob/master/getting-started/using-the-sdk.md) section its mentioned to use cosmjs v0.21.2 for demonet, but only v0.21.1 minor tag exists on the cosmjs repo. I suppose we can the documentation to v0.21.1 for now? @ethanfrey

**Comment by ethanfrey** [comment]
Typo. 0.21.1

**Comment by ethanfrey** [comment]
Wait, there was one pr after that which is required for the cli (just a helper script) that never got tagged. Maybe use that commit hash instead.

**Comment by ethanfrey** [comment]
We will update everything to 0.10 /0.22 soon enough anyway

**Comment by orkunkl** [comment]
Alright not touching it. Closing the issue
