### ISSUE TITLE
Documentation v1.0

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#212]
## Introduction

Here is the planned proposal for documentation version v1 that will be released along cw v1.0

According to the latest research, developers want API documentation along simple tutorials.

With DevRel Workgroup, making this become a platform makes more sense.

**Requirements**:

- Should have tutorials for new people
- Should have detailed documentation for the components
- Should be easily maintainable accross documentation. 
- Should be the center of events, community news.
- Should relay latest announcements.
- Some parts must be versioned(cosmwasm/rust docs).

## Layout

Docusaurus enables hosting several sections with different versioning.

This means we can host wasmd, Smart Contracts(for now rust) and CosmJs documentations and version them separately.

![](https://static.slab.com/prod/uploads/12dn8yxq/posts/images/vWFQa0JkHGoa7ysBFV83Kz9b.png)

These sub documents will be:

- **Docs**: version follows cosmwasm-std, this part will contain api and component documentation. This part could contain multiple languages in future, ideally wil just follow [code tabs](https://docusaurus.io/docs/2.0.0-beta.0/markdown-features/tabs).
- **Tutorials**: easy step by step tutorials, should be easily maintainable. Points to testnets. not versioned
  - This part corresponds to `Learn` in current docs
  - Testnet setup tutorials will be here too.
- **dApps**: Smart contracts, front ends, tooling will be listed here. when new framework is here this part will have drop down with supported languages and a general tab for other tooling.
  - cw-plus
    - cw1
    - Cw2...
  - front-ends: cw20 wallet...
  - Tooling: contract-verifier, block-explorers, IDE integrations
- **Ecosystem**: unversioned community page that will contain community content, and testnets.
  - Testnets
  - Events
  - Hall Of Fame
  - Jobs(Future work with React)
- **Forum**: maybe it is time to initiate a forum?

### Docs

**Architecture (these docs will be refactored)**

- What are Multi-chain contracts
- Actor Model for Contract Calls
- Names and Addresses
- Querying Contract State
- Serialization Formats
- Contract Composition
- Comparison with Solidity Contracts
- Native and CW20 tokens

**Smart Contracts**

**Life Cycle**

- Instantiation
- Execution
- Migration

**Components**

- Messages
  - InitMsg
  - HandleMsg(ExecuteMsg) / validation
  - MigrateMsg
- Responses
  - Result and Option usage
- State
  - KV store fundamentals
  - Singleton
  - Map
  - IndexedMap
  - ... Other cw-plus storage components
  - Show a complex example
- Handler
  - Instantiate
  - Execute
  - Migrate
- Query
- Events
- Testing
- Math
  - Unsigned Integers
  - Decimal
  - Fraction
- Migration
- Compilation
- Deployment
- Gas Usage and cost

**Migration Guide**

- Migration.md(auto track cosmwasm repo)
- Changelog.md

### IBC(TBD)

- Architecture

### Tutorials

- Smart Contracts
  - Rust(initially there this section will not exist, items below will be in the first row.)
    - Name Service
    - DAO(cw3 or cw4) as a smart contract admin
    - cw721
    - Simple Option
- Frontend dApp
- Videos and Workshops

### dApps

- cw-plus: this section will sync with cw-plus repo.
  - cw1
    - cw1-subkeys
  - …

### Ecosystem

- Events
  - Upcoming
  - Past
- Hall Of Fame
- Jobs(Future work with React)
- Relayer content?

**Comment by octalmage** [comment]
hi @orkunkl! 

I'd love to help out with some of this documentation. I think I could write some of the tutorials, are these the tutorials you had in mind? 

* Name Service
* DAO 
* Simple Option

Are there any other tutorials that you'd like to see? Possibly a CW721 tutorial would be useful.

**Comment by orkunkl** [comment]
@octalmage Hey there! Thank you so much for the help. Those tutorials are just ones that came first in my mind. 
Name service should be the high priority one. You are right it is worth adding cw721 once there is a working helper!

**Comment by orkunkl** [comment]
This issue is a proposal itself and open for recommendations.

**Comment by the-frey** [comment]
Not much to add other than this all looks good. 

I think the dApps and front-end docs/tutorials will be really useful. The need for more resources around that seems to come up pretty often AFAICT.

**Comment by Highlander-maker** [comment]
yeah i like the flow of this. A simple create smart contract tutorial would be super useful for the less coder experienced folks.

**Comment by orkunkl** [comment]
Tracked here https://github.com/InterWasm/DAO/issues/35
