### ISSUE TITLE
What is wasm32-unknown-unknown suffix?

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#22]
What is the suffix `unknown-unknown`? It looks scary when you first see it, can it be changed to something more friendly, if not what is the explanation @ethanfrey?

**Comment by ethanfrey** [comment]
Good question. It comes from rust - this is the best answer: https://users.rust-lang.org/t/wasm-unknown-vs-emscripten/22997

If you try `rustup target list`, you get something like:

```
aarch64-linux-android
i686-pc-windows-gnu
i686-unknown-freebsd
```

This is called a "target triple" and is [defined here](https://rust-lang.github.io/rfcs/0131-target-specification.html#detailed-design)

> A target triple consists of three strings separated by a hyphen, with a possible fourth string at the end preceded by a hyphen. The first is the architecture, the second is the "vendor", the third is the OS type, and the optional fourth is environment type. In theory, this specifies precisely what platform the generated binary will be able to run on

It would be nice to add this to the docs somewhere.

**Comment by orkunkl** [comment]
- [x] add to forum
- [ ] add to docs
