### ISSUE TITLE
Document 1.0

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#229]
Here are documentation overhaul for 1.0.
## Contribution
**Edit URL** will take you to github web editor. Easier than git clone.
<img width="726" alt="Screen Shot 2021-08-16 at 16 12 47" src="https://user-images.githubusercontent.com/11277600/129569426-df210f17-73ce-4d19-b7a6-fc3fc3f77e3f.png">

Links to the files will be given in the issues

- [x] #231
- [x] #232
- [x] #233
- [x] #234
- [x] #235
- [x] #236
- [x] #237
- [x] #238
- [x] #239
- [x] #240
- [x] #241
- [x] #242
- [x] #243

**Comment by 0xPaladin** [comment]
So... based on telegram talk create a "Smart Contracts" section with all the above plus these sections: Messages, Events, Testing, Math, and "Gas Usage and cost"

Will have to make sub-sections for clarity I suggest:
A: Compilation, Deployment, Instantiation, Execution, Migration (with guide), Gas Usage and cost
B: Math, State, Messages, Responses, Query, Events, Handler, Testing
