### ISSUE TITLE
Frontend App

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#240]

**Comment by 0xPaladin** [comment]
I'll work this one. I'll pull from https://docs.cosmwasm.com/tutorials/frontend-dapp/intro. 
And I'll update for clarity.

**Comment by 0xPaladin** [comment]
I just issued a pull request for the basic. 

I really think we need to work on the "standalone" app example as well.  But that is probably a nice to have considering what else is at hand.
