### ISSUE TITLE
query wasm contract ID jq error

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#26]
I am having this error: 
```sh
 CONTRACT=$(wasmcli query wasm list-contract-by-code $CODE_ID | jq -r .[0].address)

zsh: no matches found: .[0].address
```

what could be the reason?

**Comment by ethanfrey** [comment]
Maybe see what `wasmcli query wasm list-contract-by-code $CODE_ID | jq` says. as well as `echo $CODE_ID`

Did you not instantiate the contract with that CODE_ID already?

**Comment by loloicci** [comment]
Maybe a lack of logs fields in `RES` causes the issue.
```sh
# gas is huge due to wasm size... but auto-zipping reduced this from 1.8M to around 600k
# you can see the code in the result
RES=$(coral tx wasm store contract.wasm --from fred \
    --gas-prices="0.025ushell" --gas="auto" --gas-adjustment="1.2" -y)

# you can also get the code this way
CODE_ID=$(echo $RES | jq -r '.logs[0].events[0].attributes[-1].value')
```
(quoted from https://docs.cosmwasm.com/getting-started/interact-with-contract.html#go-cli)

In my environment, $RES is `{"height":"0","txhash":"...","raw_log":"[]"}`.
My environment is as follows.

- wasmcli & wasmd
  following this page: https://docs.cosmwasm.com/getting-started/setting-env.html#run-local-node-optional
- versions
```
$ wasmcli version
0.10.0

$ wasmd version  
0.10.0
```
- contract
  following https://docs.cosmwasm.com/getting-started/compile-contract.html#compiling-and-testing-contract
  (version: escrow-0.6.0)

(I executed commands replaced coral with wasmcli)

**Comment by shiki-tak** [comment]
When you run the local node, please execute the following command at the Setup client.
Then, the contents of raw_log will be returned.
`wasmcli config broadcast-mode block`

**Comment by loloicci** [comment]
It solves. Thank you, @shiki-tak !
