### ISSUE TITLE
Re-organize docs

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#41]
Requirements:
 - [x] move architecture and design details from Getting Started to Architecture to provide a basic introduction.
 - [x] add `Hijack Escrow Contract` section
 - [ ] add `Review and Verify Contract` section that uses Escrow example in Getting Started

**Comment by ethanfrey** [comment]
I would bring this down in priority now. You did the important parts for getting started. Let's do the other part later.

**Comment by orkunkl** [comment]
Closing now, Soon I will create new issues for the new structure.
