### ISSUE TITLE
Enable Algolia search

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#43]

**Comment by ethanfrey** [comment]
Very nice. Do you know how to do so with vuepress?

If it is set up for cosmos sdk docs, then I can ask those devs to help set this up... they were very supportive of the transition to vuepress

**Comment by orkunkl** [comment]
Yes, it is. Pretty easy. You put an API key and index name to `.vuepress/config.js` [reference](https://github.com/cosmos/cosmos-sdk/blob/master/docs/.vuepress/config.js#L25) and that's it. I mailed Algolia to register for DocSearch open-source program to get API key.
