### ISSUE TITLE
Add nameservice tutorial

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#6]
We can create a new tutorial explaining how to build the [nameservice contract](https://github.com/confio/cosmwasm-examples/tree/master/nameservice). Starting with an empty [cosmwasm-template](https://github.com/confio/cosmwasm-examples/tree/master/nameservice).

This can parallel the [official SDK tutorial](https://tutorials.cosmos.network/nameservice/tutorial/00-intro.html) as a guide of how to structure. Please note we can make this much simpler likely, and we can also deploy contracts on the most recent testnet.

Blockers:

- [x] Wait until 0.10 testnet is deployed to publish and update all links to that
- [ ] Ethan: record video coding this from scratch (at least some of the code - the structure) and use that as a reference when writing 

Please note there is an (old) draft PR to start this, which can be used as well: https://github.com/CosmWasm/docs/pull/37

**Comment by orkunkl** [comment]
Add advanced details that are excluded from hijacking escrow tutorial https://github.com/CosmWasm/docs2/pull/57#discussion_r468485721

**Comment by ethanfrey** [comment]
I think this can wait until later (after other issues).
Back to TODO instead of doing?
