### ISSUE TITLE
Put using smart contracts to a category of its own

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/docs-deprecated-2023#75]
Using cw20 contract documentation is [done](https://github.com/CosmWasm/testnets/issues/51). Sub keys documentation is left to close the issue. Altough the current structure is not fit for putting 2 tutorials under 1 section(`Using Smart Contracs`). Instead we should create a category(like `Learn`) and put smart contracts related docs under it. @ethanfrey

**Comment by ethanfrey** [comment]
Yeah, I am happy to do a braindump of the contract stuff and walk-throughs. And please reorganize it better to make it flow with the general narative. Not sure if it makes sense to start with this (using cw20 tokens) before even getting into contract dev.

It's nice to feel the power of tokens before digging into writing one. So, yeah, feel free to make this all better organized.
