### ISSUE TITLE
Link to video tutorials and workshops

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/docs-deprecated-2023#80]
We should list them all here.

First CodeWithUs Workshop: https://vimeo.com/436560781

Also, maybe my introduction for Unitize if you think this is a nice intro (or we can make a new video for the overview): https://vimeo.com/434654821

Make an extensible section in learn, so we can add the new one from the 26th workshop and future ones

**Comment by orkunkl** [comment]
https://vimeo.com/434654821 is private. Need to make it public to put it in the docs. @ethanfrey
